/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import hello.EurekaServiceApplication;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        EurekaServiceApplication classUnderTest = new EurekaServiceApplication();
        
    }
}
